[workspace]
members = ["tanim-cli"]
resolver = "3"

[workspace.dependencies]
typst = "0.14.2"
typst-render = "0.14.2"
tinymist-world = { version = "0.14.6", features = ["system", "fonts"]}
rsmpeg = {version = "0.18", features = ["link_system_ffmpeg"]}
