[workspace]
members = ["tanim-cli"]
resolver = "3"

[workspace.dependencies]
typst = "0.13.1"
typst-render = "0.13.1"
tinymist-world = {version = "0.13", features = ["system", "fonts"]}
rsmpeg = {version = "0.16", features = ["link_system_ffmpeg"]}